import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Header_bot from "@/components/Header_bot";
import Footer_Pmbe from "@/components/Footer_pmbe";
import { AOSInit } from '../components/aos' 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LSP PMBE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <AOSInit/>
      <body className={inter.className}>
      <Header />
      <Header_bot />
        {children}
        <Footer_Pmbe /> 
        </body>

    </html>
  );
}
